version: '3.9'

services:
  flask-app:
    image: dhiraj918106/flask_devops:latest
    ports:
      - "5000:5000"
    restart: always
    deploy:
      replicas: 3  # Run 3 instances for high availability
      restart_policy:
        condition: any
    networks:
      - flask_network

networks:
  flask_network:
    driver: overlay
